GET http://localhost:8000/students
 
###

POST http://localhost:8000/students 
content-Type: application/json

{
    "firstName": "Frank",
    "lastName": "Smith",
    "userName": "frankmith",
    "userPassword": "ASDAesdfhjbsf21",
    "userAvatarImg": "https://media.istockphoto.com/id/1300845620/vector/user-icon-flat-isolated-on-white-background-user-symbol-vector-illustration.jpg?s=612x612&w=0&k=20&c=yBeyba0hUkh14_jgv1OKqIH0CCSWU_4ckRkAoy2p73o="
}

###

PATCH http://localhost:8000/students/65cf8f30bdb12383e12ed5ea
content-Type: application/json

{
    
    "firstName": "Frank go away!!!!"
    
}

###

DELETE http://localhost:8000/students/65cf8f30bdb12383e12ed5ea

###

POST http://localhost:8000/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="2024-02-14-161247.mp4"
Content-Type: video/mp4

This is the content of the file.
----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

Post http://localhost:8000/notes
content-Type: application/json

{
    "title": "Introduction to Biology",
    "teacher": "Jane",
    "subject": "Biology",
    "body": "This course covers the basic principles of biology, including cell biology, genetics, evolution, and ecology."
}

###

Get http://localhost:8000/notes?teacher=Jane