GET http://localhost:8000/students
 
###

POST http://localhost:8000/students
content-Type: application/json

{
    "firstName": "Frank",
    "lastName": "Smith",
    "userName": "frankmith",
    "userPassword": "ASDAesdfhjbsf21",
    "userAvatarImg": "https://media.istockphoto.com/id/1300845620/vector/user-icon-flat-isolated-on-white-background-user-symbol-vector-illustration.jpg?s=612x612&w=0&k=20&c=yBeyba0hUkh14_jgv1OKqIH0CCSWU_4ckRkAoy2p73o="
}

###

PATCH http://localhost:8000/students/65cfa567943996fb1dcc9c69
content-Type: application/json

{
    
    "firstName": "Frank go away!!!!"
    
}

###

DELETE http://localhost:8000/students/65cf8f30bdb12383e12ed5ea

###

POST http://localhost:8000/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


###

# SUBJECTS

GET http://localhost:8000/subjects

###

POST http://localhost:8000/subjects 
content-Type: application/json

{
    "subject": "Chemistry"
}


###

# YEARS

GET http://localhost:8000/years

###

POST http://localhost:8000/years 
content-Type: application/json

{
    "year": "Year 13"
}




###

# QUIZ

GET http://localhost:8000/quiz

###

POST http://localhost:8000/quiz 
content-Type: application/json

{
    "quizData": [{
        "question": "Which country has the longest coastline?",
        "correct": "Canada",
        "incorrect1": "India",
        "incorrect2": "China",
        "incorrect3": "Egypt"
    },
    {
        "question": "What's the longest river in the UK?",
        "correct": "The River Severn",
        "incorrect1": "River Thames",
        "incorrect2": "River Trent",
        "incorrect3": "River Wye"
    },
    {
        "question": "What is the capital city of Portugal?",
        "correct": "Lisbon",
        "incorrect1": "Paris",
        "incorrect2": "Brussels",
        "incorrect3": "Wellington"
    },
    {
        "question": "What percentage of the world's water do rivers and lakes hold?",
        "correct": "1%",
        "incorrect1": "10%",
        "incorrect2": "23%",
        "incorrect3": "15%"
    }],
    "title": "Geography fun",
    "subject": "geography",
    "schoolyear": "9",
    "teacher": "Miss Smith"
}

###


# GET BY subject


GET http://localhost:8000/quiz?subject=geography&teacher=Miss Smith




###

DELETE http://localhost:8000/quiz/65d5d9b565a615699e4d646d


###


GET http://localhost:8000/quiz/65d48d8c276207429046b972

### Get event ###

GET http://localhost:8000/events

### Post event ###

POST http://localhost:8000/events
Content-Type: application/json

{

  "title": "Meeting with the coders",
  "start": "2024-02-20T10:00:00.000Z",
  "end": "2024-02-20T11:00:00.000Z",
  "description": "test1"

}

### Patch event ###

PATCH http://localhost:8000/events/65d61a2e98a7db509cb2161f
Content-Type: application/json

{

  "description": "Project updates"

}


### Delete Event ###

DELETE http://localhost:8000/events/65d48f41603d0046abd3d330

###

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="2024-02-14-161247.mp4"
Content-Type: video/mp4

This is the content of the file.
----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

Post http://localhost:8000/notes
content-Type: application/json

{
    "title": "Introduction to Biology111",
    "teacher": "Tim",
    "subject": "Biology",
    "body": "This course covers the basic principles of biology, including cell biology, genetics, evolution, and ecology."
}

###

Get http://localhost:8000/notes?teacher=Tim


### SUBJECTS

GET http://localhost:8000/subjects

###

POST http://localhost:8000/subjects 
content-Type: application/json

{
    "subject": "Chemistry"
}


###

# YEARS

GET http://localhost:8000/years

###

POST http://localhost:8000/years 
content-Type: application/json

{
    "year": "Year 13"
}


###

# QUIZ

GET http://localhost:8000/quiz

###
POST http://localhost:8000/quiz 
content-Type: application/json

{
    "quizData": [{
        "question": "!!!!How many years did the 100 years war last?",
        "correct": "116 years",
        "incorrect1": "100 years",
        "incorrect2": "101 years",
        "incorrect3": "99 years"
    },
    {
        "question": "Who was the first man to walk on the moon, and in which year?",
        "correct": "Neil Armstrong, 1969",
        "incorrect1": "Neil Armstrong, 1968",
        "incorrect2": "Harrison Schmitt, 1969",
        "incorrect3": "Harrison Schmitt, 1968"
    },
    {
        "question": "Which century did the French Revolution take place in??",
        "correct": "The 18th Century",
        "incorrect1": "The 17th Century",
        "incorrect2": "The 19th Century",
        "incorrect3": "The 16th Century"
    },
    {
        "question": "The Peloponnesian War was fought between Athens and which other ancient Greek state?",
        "correct": "Sparta",
        "incorrect1": "Rhodes",
        "incorrect2": "Aegina",
        "incorrect3": "Eretria"
    }],
    "title": "How good are you in History?",
    "subject": "History",
    "schoolyear": "Year 6",
    "teacher": "Miss Smith"
}
###

##GET BY subject

###
GET http://localhost:8000/quiz?schoolyear=5

###
DELETE http://localhost:8000/quiz/65d4bc4bc04c7f6ecdb3a791

###
GET http://localhost:8000/quiz/65d48d8c276207429046b972




###VIDEO COMMENTS

###
GET http://localhost:8000/videos/comment/65d4f7c062a817164048addf

###
POST http://localhost:8000/videos/comment/65d4f7c062a817164048addf
content-Type: application/json

{
    "username": "test",
    "body":"1234",
    "date": "yesterday"
}

###
delete http://localhost:8000/videos/comment/65d4f7c062a817164048addf/65d5f0ea64669227b2ac31c7

###NOTES

###
Get http://localhost:8000/notes

###
Post http://localhost:8000/notes
content-Type: application/json

{
    "title": "Introduction to Biology111",
    "teacher": "Tim",
    "subject": "Biology",
    "body": "This course covers the basic principles of biology, including cell biology, genetics, evolution, and ecology."
}

###
Get http://localhost:8000/notes/65d49312fc287ca6784ad42c

###
Get http://localhost:8000/notes/comment/65d49036fc287ca6784ad427

###
Post http://localhost:8000/notes/comment/65d49036fc287ca6784ad427
content-Type: application/json

{
    "username": "john",
    "body":"this is so educational!!!!",
    "date": "today"
}

###
delete http://localhost:8000/notes/comment/65d49036fc287ca6784ad427/65d61648bd1d7e7e58286030

###

Post http://localhost:8000/notes/image/65d4b8a47dbd8584b0c284e3
content-Type: application/json

{
    "img_title": "bug",
    "img_url": "https://ichef.bbci.co.uk/images/ic/976xn/p0cgdvxh.png"
}

###

Get http://localhost:8000/notes